mutation InsertUserFamilhar(
  $id: Uuid!,
  $nome: String!,
  $sobrenome: String!,
  $sexo: Boolean!,

  $email: String!,
  $senha: String!,
  $data_nascimento: Date!,
  $data_criacao: Date!,
  
  $local_trabalho: String!,

){
  user_familhar: insertusuario_familhar(value: {
    id: $id,
    nome: $nome,
    sobrenome: $sobrenome,
    sexo: $sexo,

    email: $email,
    hash_senha: $senha,
    
    data_nascimento: $data_nascimento,
    data_criacao: $data_criacao,

    local_trabalho: $local_trabalho
    
  }){
    value{
      id,
      nome,
      sobrenome
    }
  }
}