mutation InsertUserEspecialista(
  $id: Uuid,
  $nome: String,
  $sobrenome: String
  $sexo: Boolean,

  $email: String,
  $senha: String,
  $idade: TinyInt,
  $data_nascimento: Date,
  $data_criacao: Date,
  
  $crm: String,
  $local_trabalho: String,

){
  user_especialista: insertusuario_especialista(value: {
    id: $id,
    nome: $nome,
    sobrenome: $sobrenome,
    sexo: $sexo,

    email: $email,
    hash_senha: $senha,
    
    idade: $idade,
    data_nascimento: $data_nascimento,
    data_criacao: $data_criacao,

    crm: $crm
    local_trabalho: $local_trabalho
    
  }){
    value{
      id,
      nome,
      sobrenome
    }
  }
}