name: MedTempo Ruby Backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Build Docker Container
        uses: docker/build-push-action@v4
        with: 
          context: .     
      - 
        name: Make Testes 
        run: docker images
          
      
