name: MedTempo Ruby Backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Build Docker Container
        run: docker build -t medtempo-backend --file Dockerfile --target test .
        
      - 
        name: Teste
        run: ls -la
