name: MedTempo Ruby Backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: MedTempo Ruby Backend
    - uses: actions/checkout@v3
    - run: docker build -t medtempo-backend --file Dockerfile --target test .
